# Generated by Django 2.1.5 on 2020-07-16 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('intro', models.CharField(max_length=300, verbose_name='文章简介')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章正文')),
                ('time', models.DateField(verbose_name='发布时间')),
                ('number', models.IntegerField(verbose_name='阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户一对一外键')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('name', models.CharField(max_length=10, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sort', verbose_name='分类外键'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联USER模型，一对一'),
        ),
    ]
